### ISSUE TITLE
Can't install on Android

### ISSUE THREAD

**Issue by igor-bv** [tectiv3/react-native-aes#1]
RN v0.44
on installation process got this errors:
`
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:52: error: no suitable method found for decrypt(String,String,String)
            String strs = decrypt(data, pwd, iv);
                          ^
    method RCTAes.decrypt(String,String,String,Callback,Callback) is not applicable
      (actual and formal argument lists differ in length)
    method RCTAes.decrypt(String) is not applicable
      (actual and formal argument lists differ in length)
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:82: error: method sha256 in class RCTAes cannot be applied to given types;
            String strs = sha256(data);
                          ^
  required: String,Callback,Callback
  found: String
  reason: actual and formal argument lists differ in length
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:92: error: method sha1 in class RCTAes cannot be applied to given types;
            String strs = sha1(data);
                          ^
  required: String,Callback,Callback
  found: String
  reason: actual and formal argument lists differ in length
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:102: error: method sha512 in class RCTAes cannot be applied to given types;
            String strs = sha512(data);
                          ^
  required: String,Callback,Callback
  found: String
  reason: actual and formal argument lists differ in length
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:114: error: cannot find symbol
            SecretKey secret = new SecretKeySpec(tmp.getEncoded(), KEY_ALGORITHM);
                                   ^
  symbol:   class SecretKeySpec
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:129: error: cannot find symbol
        return pwd;
               ^
  symbol:   variable pwd
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:133: error: cannot find symbol
        Thread.sleep(randomInt.nextInt(100));
                     ^
  symbol:   variable randomInt
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:140: error: cannot find symbol
            cipher.init(Cipher.ENCRYPT_MODE, getSecretKey(pwd), sr);
            ^
  symbol:   variable cipher
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:141: error: cannot find symbol
            encrypted = cipher.doFinal(text.getBytes("UTF-8"));
                        ^
  symbol:   variable cipher
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:150: error: cannot find symbol
        Thread.sleep(randomInt.nextInt(100));
                     ^
  symbol:   variable randomInt
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:157: error: cannot find symbol
            cipher.init(Cipher.DECRYPT_MODE, getSecretKey(pwd), cr);
                                                          ^
  symbol:   variable pwd
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:157: error: cannot find symbol
            cipher.init(Cipher.DECRYPT_MODE, getSecretKey(pwd), cr);
                                                                ^
  symbol:   variable cr
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:157: error: cannot find symbol
            cipher.init(Cipher.DECRYPT_MODE, getSecretKey(pwd), cr);
            ^
  symbol:   variable cipher
  location: class RCTAes
node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAes.java:158: error: cannot find symbol
            decrypted = cipher.doFinal(Base64.decode(code, Base64.DEFAULT));
                        ^
  symbol:   variable cipher
  location: class RCTAes
14 errors
`

thanks for help in advance!

**Comment by tectiv3** [comment]
yeah, I don't have android, so I wrote this code blindly :) Pull requests are welcome.

**Comment by bitsal** [comment]
@igor-bv please verify if it works for you now

**Comment by tectiv3** [comment]
fixed!
