### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by SeriousMatters** [tectiv3/react-native-aes#11]
Can't build for android on a clean project

#### What I did
$ react-native init dummyProject
$ cd dummyProject
$ npm install --save react-native-aes-crypto
$ react-native link react-native-aes-crypto
$ react-native run-android
// without even importing it in js code

#### the error message

$ react-native run-android
Scanning folders for symlinks in /home/me/Projects/dummyProject/node_modules (15ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-aes-crypto:preBuild UP-TO-DATE
:react-native-aes-crypto:preReleaseBuild UP-TO-DATE
:react-native-aes-crypto:checkReleaseManifest
:react-native-aes-crypto:preDebugAndroidTestBuild UP-TO-DATE
:react-native-aes-crypto:preDebugBuild UP-TO-DATE
:react-native-aes-crypto:preDebugUnitTestBuild UP-TO-DATE
:react-native-aes-crypto:preReleaseUnitTestBuild UP-TO-DATE
:react-native-aes-crypto:prepareComAndroidSupportAppcompatV72301Library
:react-native-aes-crypto:prepareComAndroidSupportSupportV42301Library
:react-native-aes-crypto:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-aes-crypto:prepareComFacebookFrescoDrawee130Library
:react-native-aes-crypto:prepareComFacebookFrescoFbcore130Library
:react-native-aes-crypto:prepareComFacebookFrescoFresco130Library
:react-native-aes-crypto:prepareComFacebookFrescoImagepipeline130Library
:react-native-aes-crypto:prepareComFacebookFrescoImagepipelineBase130Library
:react-native-aes-crypto:prepareComFacebookFrescoImagepipelineOkhttp3130Library
:react-native-aes-crypto:prepareComFacebookReactReactNative0510Library
:react-native-aes-crypto:prepareComFacebookSoloaderSoloader010Library
:react-native-aes-crypto:prepareOrgWebkitAndroidJscR174650Library
:react-native-aes-crypto:prepareReleaseDependencies
:react-native-aes-crypto:compileReleaseAidl
:react-native-aes-crypto:compileReleaseNdk UP-TO-DATE
:react-native-aes-crypto:compileLint
:react-native-aes-crypto:copyReleaseLint UP-TO-DATE
:react-native-aes-crypto:compileReleaseRenderscript
:react-native-aes-crypto:generateReleaseBuildConfig
:react-native-aes-crypto:generateReleaseResValues
:react-native-aes-crypto:generateReleaseResources
:react-native-aes-crypto:mergeReleaseResources
:react-native-aes-crypto:processReleaseManifest
:react-native-aes-crypto:processReleaseResources
:react-native-aes-crypto:generateReleaseSources
:react-native-aes-crypto:incrementalReleaseJavaCompilationSafeguard
:react-native-aes-crypto:compileReleaseJavaWithJavac
:react-native-aes-crypto:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/me/Projects/dummyProject/node_modules/react-native-aes-crypto/android/src/main/java/com/tectiv3/aes/RCTAesPackage.java:23: error: method does not override or implement a method from a supertype

    @Override
    ^
1 error
:react-native-aes-crypto:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-aes-crypto:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.202 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by romandubrov** [comment]
I have same issue
"react-native": "0.52.0",
"react-native-aes-crypto": "^1.2.0"

**Comment by tectiv3** [comment]
Should be fine now.
