### ISSUE TITLE
Example code in README.MD results in Promise error

### ISSUE THREAD

**Issue by ewalti** [tectiv3/react-native-aes#15]
I'm new to crypto and giving this library a whirl to AES256 encrypt some files on the iOS filesystem. Unfortunately using the example in the README.MD results in an `Error: Encrypt error`. 

I'm not quite sure what this error is coming from. 

I've replaced the `ivBase64` bit with a random generated string from `CryptoJS`. This could be the source of the error?

**Comment by deepmehtait** [comment]
@ewalti: I am getting similar issues with the library. Getting error of `AES error, -4310`

**Comment by Kelmatou** [comment]
Hey I'm having the same error, I tried many things to make it work, unsuccessfully :(
Did anyone find a solution?

**Comment by tectiv3** [comment]
Sorry guys, I don't do RN development anymore, so I can't update lib to be compatible with current Xcode and RN versions. 
PRs are welcome, though.

**Comment by svipben** [comment]
@tectiv3 I managed to fix this issue. PR is coming soon, it will be very good if you will be able to review it, merge it and then release it.

**Comment by svipben** [comment]
Already opened a PR: https://github.com/tectiv3/react-native-aes/pull/17

**Comment by tectiv3** [comment]
Fixed
