### ISSUE TITLE
pod install fails to run

### ISSUE THREAD

**Issue by mxmauro** [tectiv3/react-native-aes#22]
Hi,

When you run `pod install` to run an app in iOS, it complains about the empty summary string located in
`react-native-aes.podspec` file.

Can you add some description?

Thanks,
Mauro.

**Comment by tectiv3** [comment]
Can you try again please? I've added a summary :)

**Comment by mxmauro** [comment]
I'll do! Thanks for the quick answer.

**Comment by binhndicts** [comment]
I also got this problem
```
Fetching podspec for `react-native-aes` from `../node_modules/react-native-aes-crypto`
[!] The `react-native-aes` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | source: Git sources should specify a tag.
    - WARN  | github_sources: Github repositories should end in `.git`.
```

and was able to solve it by just put some texts to `summary` field of `react-native-aes.podspec` file
