### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xploSEoF** [tectiv3/react-native-aes#24]
The documentation doesn't make text encoding clear at all.

It would seem:
- base16 (hexadecimal):
    - `iv` from `randomKey`
    - `iv` for `encrypt`
    - `iv` for `decrypt`
    - `key` on iOS for `encrypt` (despite being called base64key in the JS code)
    - `key` on iOS for `decrypt` (despite being called base64key in the JS code)
- base64:
    - `cipher` from `encrypt` (no padding characters given)
    - `cipher` for `decrypt` (padding characters allowed but not required)

I haven't checked the other functions yet, but this was rather confusing to find out.

**Comment by tectiv3** [comment]
yep, you were right, thank you for catching those leftovers from refactoring.
