### ISSUE TITLE
Different algorithms used on each platform

### ISSUE THREAD

**Issue by xploSEoF** [tectiv3/react-native-aes#25]
By the looks of things, this library uses AES-256-CBC on Android, and AES-128-CBC on iOS... this should be more consistent.

**Comment by tectiv3** [comment]
yeah, probably.
I don't think you can specify it on android though so we can't change it there.
I'll gladly accept PR for iOS :)

**Comment by 3bodyZZ** [comment]
> 
> 
> yeah, probably.
> I don't think you can specify it on android though so we can't change it there.
> I'll gladly accept PR for iOS :)

hey, is iOS algorithm fixed yet ?

**Comment by tectiv3** [comment]
Yup

**Comment by tuannm2** [comment]
> Yup

I still get different result when encrypt on IOS and android. How can I fix it.
