### ISSUE TITLE
PBKDF2 on Android?

### ISSUE THREAD

**Issue by mobitar** [tectiv3/react-native-aes#3]
Looks like there's no PBKDF2 support on Android yet? Probably should have mentioned this in the readme ;)

**Comment by tectiv3** [comment]
https://github.com/tectiv3/react-native-aes/blob/2a2cbaf96a64fee7329731ae3970b76f9e06d83c/android/src/main/java/com/tectiv3/aes/RCTAes.java#L63
Though I don't have any android devices so I can't test it myself

**Comment by mobitar** [comment]
That's just the wrapper though. The actual method is not implemented: https://github.com/tectiv3/react-native-aes/blob/master/android/src/main/java/com/tectiv3/aes/RCTAes.java#L120

I have a fork where I implemented it using BouncyCastle: https://github.com/mobitar/react-native-aes/blob/master/android/src/main/java/com/tectiv3/aes/RCTAes.java#L173

**Comment by tectiv3** [comment]
Nice!
Pull requests are welcome :)

**Comment by mobitar** [comment]
Ok, will do. However Android Studio added a bunch of irrelevant files, so I have to clean that up first. If I don't get the chance it might just be worth it to copy/paste the changes.

**Comment by tectiv3** [comment]
okay, I'll add it myself then!

**Comment by tectiv3** [comment]
7a2cc162843071a7f72195845c7c3086f31cf96f
Can you please check it out and then I'll push a new version to npm if it's working.
Thank you.

**Comment by mobitar** [comment]
Looks good to me! Only thing is if you plan on exposing the randomKey and randomUuid methods, you should add them to iOS as well.
