### ISSUE TITLE
Sample code: encryption method throwing error "Unsupported key size: 64 bytes" in android emulator

### ISSUE THREAD

**Issue by richard-buckingham** [tectiv3/react-native-aes#31]
Hey Guys,

I'm having issues running the sample code listed on https://github.com/tectiv3/react-native-aes on an android emulator. We're using the current version ( 1.3.6 );

I'm running on Windows 10, using an android emulator running Android Pie.

We copied and pasted the sample code from github. The only difference was adding a catch statement to the encrypt function so that the error was caught.

The error message is "Error: Unsupported key size: 64 bytes". and occurs on the third line of the function shown below.

encrypt = (text, key) => {
    return Aes.randomKey(32).then(iv => {
      return Aes.encrypt(text, key, iv)
        .then(cipher => ({
          cipher,
          iv,
        }))
        .catch(error => {
          console.log('encryption failed, error is ', error);
        });
    });
  };

I was wondering whether react-native-aes supports Android.  If so, and anyone has seen this issue before, is there a workaround?

**Comment by tectiv3** [comment]
change the length from 512 to 256
```
generateKey('Arnold', 'salt', 5000, 256).
```
change the length from 32 to 16
```
return Aes.randomKey(16)
```
