### ISSUE TITLE
TypeError: Cannot read property 'randomKey' of undefined

### ISSUE THREAD

**Issue by carlos03** [tectiv3/react-native-aes#33]
I am using `react-native 0.61.5`
I follow the example of the documentation
```
import {NativeModules, Platform} from 'react-native'
var Aes = NativeModules.Aes
```
and I have the following error:

`TypeError: Cannot read property 'randomKey' of undefined`

please help

**Comment by tectiv3** [comment]
ios? android?
if you are on iOS run `pod install` in ios folder.

**Comment by janneman001** [comment]
Same here on ios. pod install does not help.
react-native 0.59.9

**Comment by nonameb3** [comment]
same here "TypeError: Cannot read property 'pbkdf2' of undefined" on react-native 0.62.2

**Comment by MusabBasheer** [comment]
You can use it like this and it will work


import { NativeModules } from 'react-native'

const EncryptionHelper = {
    generateKey: async (password: any, salt: any, cost: any, length: any) => {
        var Aes = NativeModules.Aes;
        return await Aes.pbkdf2(password, salt, cost, length)
    },
    decryptData: async (encryptedData: { cipher: any; iv: any; }, key: any) => {
        var Aes = NativeModules.Aes;
        return await Aes.decrypt(encryptedData.cipher, key, encryptedData.iv)
    },
    generateIV: async () => {
        var Aes = NativeModules.Aes;
        return await Aes.randomKey(16)
    },
    encryptData: async (text: any, key: any, iv: any) => {
        var Aes = NativeModules.Aes;
        return await Aes.encrypt(text, key, iv);
    }
}
export default EncryptionHelper;
