### ISSUE TITLE
Decryption always fails.

### ISSUE THREAD

**Issue by exotexot** [tectiv3/react-native-aes#34]
Im using the example from the README.
Encryption works without issues.

Decryption always fails. 

Im using RNFS to read a File, then passing the base64 encoded contents to the decrypt function. Console information arent really revealing (to me)

![Screenshot 2020-03-12 at 15 39 50](https://user-images.githubusercontent.com/10153413/76533076-cc517e00-6477-11ea-9afb-ce4d20b924c4.png)

**Comment by gitmazzio** [comment]
Same for me.

**Comment by tectiv3** [comment]
This is how it was used by me:
https://github.com/tectiv3/amanothi/blob/master/src/Storage.js#L229
and this is how it is being used by Standard Notes:
https://github.com/standardnotes/mobile/blob/master/src/lib/sfjs/sfjs.js

**Comment by MarvynORourke** [comment]
Same for me. When I log the error I have this: 

`03-23 12:44:09.708  4645  4801 I ReactNativeJS:[Error: bad base-64]
03-23 12:44:09.711  4645  4801 I ReactNativeJS: [Error: bad base-64]`

and sometimes :

`[Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT]`

**Comment by tectiv3** [comment]
Don't forget to save `iv` used for encrypting, you'll need it for decryption. Also you should check HMAC to make sure data isn't corrupted. Look for examples by following the links I posted above.

**Comment by farbexot** [comment]
I solved my problem by following the examples provided by tectiv3. Thanks!

**Comment by farbexot** [comment]
Hello,

are there some constraints regarding the keys and iv?

For example, I can use keys and ivs like these
let Akey = "cece3a7dc9cf86aae926fd2ee520a06e5a5b616fa9e381de53600121e8aff095"
let Aiv = "4e58cafb7b6ccbbef797c2761b233a58"

But If I change a the key to test, encryption works like normal. But the decryption fails with those parameters.
let Akey = "test"
let Aiv = "4e58cafb7b6ccbbef797c2761b233a58"

I'm using to encrypt
const encrypted = await NativeModules.Aes.encrypt(data, Akey, Aiv)


I'm using to decrypt:
const decrypted = await NativeModules.Aes.decrypt(data, Akey, Aiv)

But it still throws me the error that I posted initially.

**Comment by farbexot** [comment]
Yes,

If I create a key like so:
await NativeModules.Aes.pbkdf2(ref, startTime.toString(), 1000, 256)

I need to make sure that the last value, is at least 256. Otherwise the decryption process fails for me.

**Comment by tectiv3** [comment]
yes, you need to derive a key from your password phrase

**Comment by vilmes21** [comment]
> Yes,
> 
> If I create a key like so:
> await NativeModules.Aes.pbkdf2(ref, startTime.toString(), 1000, 256)
> 
> I need to make sure that the last value, is at least 256. Otherwise the decryption process fails for me.

I agree with the > 256 length idea. I copied code directly from readme.md and it consistently fails if length was set to 128. When set to 256, it works. Please someone look into this.

**Comment by vilmes21** [comment]
> yes, you need to derive a key from your password phrase

I don't think this is the point the other user was hinting at. The issue was with the `length` argument. When set to `256`, things work fine. When set to, for example, `128`, things fail. You can even try with the readme.md sample code. Behaves very consistenly.
