### ISSUE TITLE
 Exception in HostFunction: encryption of large base64 encoded files fail.

### ISSUE THREAD

**Issue by exotexot** [tectiv3/react-native-aes#35]
Hi,

I'm using react-native-fs to download a PDF. Once the download is complete, the File is being parsed as base64, and then encrypted with react-native-aes. On completion the file is being written to the local storage and the original unencrypted file deleted.

The PDFs can be quite large, lets assume up to 100mb. If the filesize is over roughly 20mb, the Encryption process fails. In my metro console I get the error message.

[Error: Exception in HostFunction: Malformed calls from JS: field sizes are different.
[[79,51],[0,0],[[749,2000,1585824394783,false]],6421]]

**Comment by tectiv3** [comment]
Hi, first of all wow I never tried to use it like this!
what platform is it failed on? or is it both?

**Comment by farbexot** [comment]
Currently I test primarily with iOS devices.
Hm, I'm also kind of new to this, are there other ways of encrypting binary files in react-native that you are aware of?
