### ISSUE TITLE
iOS decryption fails, android decrypts without issue

### ISSUE THREAD

**Issue by thijs-qv** [tectiv3/react-native-aes#36]
Decrypting on iOS fails, while on Android the string is decrypted without errors.
Example:
cipher: `lsLO2/zWc94N+44ITrIcZg==`
iv: `81d547af495555646396903bf93f7535`
key: `04925eeaefd0d2a91cc5b7e341b9c420`

Returns `976354` on Android (the correctly decrypted string) but results in `Error: Decrypt failed at createErrorFromErrorData` on iOS.

**Comment by thijs-qv** [comment]
Issue ended up being the key size.

**Comment by tcz** [comment]
@thijs-qv can you elaborate?

**Comment by thijs-qv** [comment]
This key `04925eeaefd0d2a91cc5b7e341b9c420` is a AES-128 key (16 bytes). If you take a look at [AesCrypt.m](https://github.com/tectiv3/react-native-aes/blob/fc0ef50412158c6dd3b0b5b73113e338ce237308/ios/RCTAes/lib/AesCrypt.m#L66) you can see that there is a method to decrypt with a AES-256 key, but not one to decrypt with a AES-128 key.
