### ISSUE TITLE
Can I set sha512 length to 32 bytes?

### ISSUE THREAD

**Issue by ihormihal** [tectiv3/react-native-aes#4]
Great work! I was looking for alternative to node crypto library for react-native. But I have some questions. How I can set key length option? I need 64 bytes key length instead 128. Thanks.
I can redefine CC_SHA512_DIGEST_LENGTH and CC_SHA512_BLOCK_BYTES in AesCrypt.m lib but can you add this feature into package?

**Comment by amerbashoeb** [comment]
Hi there,

I am also after this feature. Any update?

**Comment by tectiv3** [comment]
CC_SHA512_DIGEST_LENGTH is 64 bytes.

**Comment by tectiv3** [comment]
yes, pbkdf2 method now has a length parameter
