### ISSUE TITLE
AES 256 returns 64 bit key , Is this maximum limit ?

### ISSUE THREAD

**Issue by Sayyamabbasi786** [tectiv3/react-native-aes#43]
hey geeks! I have just run react-native-aes-crypto example same as given in the documentation, the thing I have noticed that it returns 64-bit key 

Key: cece3a7dc9cf86aae926fd2ee520a06e5a5b616fa9e381de53600121e8aff095
Encrypted: dTjh9XV3tRl5cKGgi25h/RXnOND+F4vle6cLl7V2Pc8ye3xwdfxq8a/yWv5cDaVt
Decrypted: These violent delights have violent ends

is this is the maximum or minimum limit?

**Comment by ProdigySim** [comment]
That key appears to be written in a hexadecimal format. 64 hexadecimal character is actually 1024 bits.
