### ISSUE TITLE
[Error: Decrypt failed]

### ISSUE THREAD

**Issue by thechaudharysab** [tectiv3/react-native-aes#49]
I used this online tool [https://www.javainuse.com/aesgenerator](https://www.javainuse.com/aesgenerator) to generate this example data:

```
    const encryptedData = {
        cipher: "OuCmv1nXCzfy+529oeJU8g==",
        iv: "1234123412341234",
        key: "56785678567856785678567856785678"
    }
```

While encrypting the Mode selected is `CBC`, the Key Size is `256` bits, the output format is `base64`. in react native this is how I'm decrypting it:

```
import { NativeModules } from 'react-native';
var Aes = NativeModules.Aes

...

    async function asyncDecrypt(cipher, key, iv) {
        try {
            var text = await Aes.decrypt(cipher, key, iv)
            return text
        } catch (e) {
            console.error(e)
        }
    }

    console.log(asyncDecrypt(encryptedData.cipher, encryptedData.key, encryptedData.iv))
```

I'm getting `[Error: Decrypt failed]` and `console.log` prints `{"_U": 0, "_V": 0, "_W": null, "_X": null}`
@tectiv3

**Comment by aalhitennf** [comment]
you need to await for the asyncDecrypt
