### ISSUE TITLE
compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by sasi-cognox** [tectiv3/react-native-aes#52]
I'm trying to run Metamask app on my local setup & it uses `react-native-aes-crypto`

The failure details are below:
![AES Crypto](https://user-images.githubusercontent.com/85170247/121202675-18fe5180-c893-11eb-93f2-8cb4ab7acb5e.png)
Please Help!

**Comment by neel-thakker** [comment]
comment the function which is present at 95th line

**Comment by tectiv3** [comment]
Yeah, this method is not from this lib.
