### ISSUE TITLE
index.d.ts is not a module.

### ISSUE THREAD

**Issue by gigeos** [tectiv3/react-native-aes#58]
Hello!
Thank you for your job! But I have a typing issue with version 1.3.10

When I do:
`import Aes from 'react-native-aes-crypto'`

I have the following issue:
`File '/node_modules/react-native-aes-crypto/index.d.ts' is not a module`

**Comment by jhartmanlinus** [comment]
i get this issue as well

**Comment by huydv92** [comment]
Hello. 
Could you help me fix this bug? I also can't import this library
