### ISSUE TITLE
Android implementation doesn't respect "algorithm" (2.0.0) and depends only on key length

### ISSUE THREAD

**Issue by vixentael** [tectiv3/react-native-aes#61]
In version 2.0.0 there's a new field algorithms that allows changing key length for AES-CBC encryption/decryption:

https://github.com/tectiv3/react-native-aes/blob/6e804012f79d61e5c85f1b26580397d40d4ff82a/index.d.ts#L3-L7

iOS implementation respects the field `algorithms` and changes key length:

https://github.com/tectiv3/react-native-aes/blob/6e804012f79d61e5c85f1b26580397d40d4ff82a/ios/RCTAes/lib/AesCrypt.m#L66-L86

Android implementation fully ignores the field `algorithms`:

https://github.com/tectiv3/react-native-aes/blob/6e804012f79d61e5c85f1b26580397d40d4ff82a/android/src/main/java/com/tectiv3/aes/RCTAes.java#L58-L62

Also, Android implementation doesn't configure AES key length (neither in 2.0.0, nor in 1.3.10):

https://github.com/tectiv3/react-native-aes/blob/6e804012f79d61e5c85f1b26580397d40d4ff82a/android/src/main/java/com/tectiv3/aes/RCTAes.java#L200-L211

~Based on docs ([oracle](https://docs.oracle.com/javase/9/docs/api/javax/crypto/Cipher.html)), I believe that Android implementation always uses AES-128-CBC.~
~You can check this encrypting value using AES-256-CBC on iOS and then trying to decrypt on Android – decryption should fail. This issue #36 kinda supports my guess.~

@tectiv3 could you please clarify, if my guess is correct, and Android implementation always uses AES-128-CBC?

**UPDATE**: based on @tectiv3 response, Android depends only on the actual key length sent to the function. Thus, if `AES-256-CBC` is specified, but the key has 16 bytes, then `AES-128-CBC` will be used with any warning.

**Comment by tectiv3** [comment]
You are correct. Please refer to https://github.com/tectiv3/react-native-aes/pull/46

**Comment by vixentael** [comment]
So, Android depends only on the actual key length sent to the function. Thus, if AES-256-CBC is specified, but the key has 16 bytes, then AES-128-CBC will be used with any warning.

**Comment by vixentael** [comment]
I'd recommend explicitly saying this in the Readme, or even better, verify key length and selected cipher and send warning / return error to the users.

**Comment by tectiv3** [comment]
@vixentael feel free to open a pull request and contribute! :)
