### ISSUE TITLE
Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by nakulsaini** [tectiv3/react-native-aes#64]
Android build failing with `Plugin with id 'maven' not found` error.
React Native Version: 0.67.2

Temporarily fixed it by following change:
`apply plugin: 'maven'` to `apply plugin: 'maven-publish'`
at file _./node_modules/react-native-aes-crypto/android/build.gradle_

**Comment by tectiv3** [comment]
>In Gradle 7.x,

>The maven plugin has been removed. You should use the maven-publish plugin instead.

**Comment by AndreaGProg** [comment]
in
./node_modules/react-native-aes-crypto/android/build.gradle
change this
apply plugin: 'maven'
with
apply plugin: 'maven-publish'
