### ISSUE TITLE
RCTAes.decrypt got 5 arguments expected 6

### ISSUE THREAD

**Issue by ambessh** [tectiv3/react-native-aes#66]
**I got this error after upgrading all dependecies.**
 _code below_

> await NativeModules.Aes.decrypt(
>                         content,
>                         key,
>                         'b1cb4d457f7640cafaefc9fd74e5fdfd',
>                       );

**Comment by tectiv3** [comment]
from the readme:
```
Aes.decrypt(encryptedData.cipher, key, encryptedData.iv, 'aes-256-cbc')
```
