### ISSUE TITLE
Android pbkdf2 cost and length

### ISSUE THREAD

**Issue by gaosusan** [tectiv3/react-native-aes#7]
Hi,
I noticed that the pbkdf2 implementation for android has been updated. I'm currently getting an error of:
"RCTAes.pbkdf2 got 4 arguments, expected 6"
which I'm assuming is from only passing in the pwd and salt with:
const generateKey = (password, salt) => Aes.pbkdf2(password, salt);
when the android implementation also requires additional parameters of length and cost. I don't know much about pbkdf2, is there a recommended/default cost and length? Also, I'm assuming the readme needs to be updated with a seperate android vs ios implementation for pbkdf2?

**Comment by tectiv3** [comment]
You are right, they should be compatible.
Fixed in https://github.com/tectiv3/react-native-aes/commit/714899569610577d568e96dedd8c31a53b72eadd , can you please verify it works? (I don't have an android device)
