### ISSUE TITLE
Android(13) and iOS both builds are Crashing on version 2.0.1

### ISSUE THREAD

**Issue by gayatrimhaske-eaton** [tectiv3/react-native-aes#79]
Updated the latest version of react-native-aes-crypto lib 3.0.1 Locally I can see the encrypted and decrypted value on the simulator but same changes are causing Crash on Real Device Both Android and iOS. is there any solution on this?

**Comment by DivyaniPatel96** [comment]
@gayatrimhaske-eaton Did you find any solution for this issue? I am also facing same issue.
Thanks.
