### ISSUE TITLE
Presenting problems to Encrypt data with the README demo

### ISSUE THREAD

**Issue by gasparnd** [tectiv3/react-native-aes#80]
I have an app with React Native v0.71.8 and  "react-native-aes-crypto": "^3.0.1"

I cannot Encrypt data with the demo code in the Readme:

```
const encryptData = (text, key) => {
  return Aes.randomKey(16).then((iv) => {
    return Aes.encrypt(text, key, iv, "aes-256-cbc").then((cipher) => ({
      cipher,
      iv,
    }));
  });
};

export const decryptData = async () => {
 
  const res = encryptData("Flexit", "test34");

  return res;
};
```

**Comment by lefrankleal** [comment]
have you found solution to this? maybe error message would give us idea of what is going on with your code

**Comment by tectiv3** [comment]
https://github.com/tectiv3/react-native-aes-demo

look at the demo project
