### ISSUE TITLE
Apple Export Compliance 

### ISSUE THREAD

**Issue by LCseniordev** [tectiv3/react-native-aes#85]
Hello, I'm curious to know if anyone has successfully used this library to publish an app on the App Store.

According to the export compliance guidelines on Apple's website (https://help.apple.com/app-store-connect/#/devc3f64248f), it's mentioned that apps which only utilize the encryption provided by the Apple operating system do not need additional documentation.

Would this library qualify under that specification?

Thanks!

**Comment by tectiv3** [comment]
I think yeah cause all it does - is binds to the native methods: https://github.com/tectiv3/react-native-aes/blob/master/ios/RCTAes/lib/AesCrypt.m

**Comment by LCseniordev** [comment]
Thank you for a quick response!
