### ISSUE TITLE
Please upgrade android to a newer gradle

### ISSUE THREAD

**Issue by alister-hbf** [tectiv3/react-native-aes#86]
I'm using this in a gradle 8.2.2 app and it needs a namespace for dependent libraries. 
I'm just suggesting you bump this to a gradle that supports namespace like 7 but I would really like it to be at 8.
I had a crack at it myself but I'm no expert check my half baked attempt here: https://github.com/alister-hbf/react-native-aes/pull/1

**Comment by tectiv3** [comment]
Tried it with latest react-native project, it didn't care much about lib graddle version. updated the demo:
https://github.com/tectiv3/react-native-aes-demo
