### ISSUE TITLE
Encryption and Decryption is not working with Android Real device and for Emulator I am able to see the encrypted and decrypted value.

### ISSUE THREAD

**Issue by DivyaniPatel96** [tectiv3/react-native-aes#87]
react-native-aes-crypto : 3.0.2
react-native: 0.72.5

**Comment by tectiv3** [comment]
just tried it. setup a new project. installed the library.

run example from the readme - both ios simulator and android real device - zero problems.

**Comment by tectiv3** [comment]
updated demo: https://github.com/tectiv3/react-native-aes-demo

**Comment by lozyloop12** [comment]
Hi @tectiv3 
when using the code example in demo:
const encryptData = (text, key) => {
    return Aes.randomKey(16).then(iv => {
        return Aes.encrypt(text, key, iv, 'aes-256-cbc').then(cipher => ({
            cipher,
            iv,
        }))
    })
}

I got the error key length not 128/192/256 bits
Can you help me check with real android device, real ios device working. good

**Comment by tectiv3** [comment]
```
 generateKey('Arnold', 'salt', 5000, 256).then(key => {
      console.log('Key:', key);
```
this is key generation

**Comment by lozyloop12** [comment]
@tectiv3 Thanks, i got the error 

generateKey('Arnold', 'salt', 5000, 256) -> encrypt success
generateKey('Arnold', 'salt', 128, 16) -> encrypt failure

-> I dont know why got error with Aes.encrypt(text, key, iv, "aes-128-ctr")

**Comment by tectiv3** [comment]
>I got the error key length not 128/192/256 bits

16 is length - so you can't use 16 :)
