### ISSUE TITLE
Error generating random key: [TypeError: Cannot read property randomKey of null]

### ISSUE THREAD

**Issue by Frankelly-001** [tectiv3/react-native-aes#95]
This works on debug mode, but not on release i keep getting this error “Cannot read property randomKey of null“ even though i have updated to the latest version, i am stuck on making the next release on production
![3b994333-97aa-48eb-b68a-d94aeae87dff](https://github.com/user-attachments/assets/e66290f0-7bb5-4284-8255-37996f4485d6)

Platform: IOS & Android

**Comment by tectiv3** [comment]
https://github.com/tectiv3/react-native-aes/issues/89
