### ISSUE TITLE
AES is null on real device and simulator (IOS and Android)

### ISSUE THREAD

**Issue by frankelly001** [tectiv3/react-native-aes#96]
i tried logging AES and getting error of some properties like randomKey, encrypt, decrypt is null, i have been using this module without having any issues for a long time abt 2 years now.
Am now facing this weird error, can't push this changes to prod.

**Comment by bohdanbirdie** [comment]
For now this is what helped me on ios, haven't tried android
```ts
import { NativeModules } from "react-native";
import AesLib from "react-native-aes-crypto";
const Aes: typeof AesLib = NativeModules.Aes;
```

**Comment by tectiv3** [comment]
https://github.com/tectiv3/react-native-aes/issues/89
